# SERVER PROPERTIES
server:
  port: 9001

#SPRING APPLICATION NAME
spring:
  application:
    name: DEPARTMENT-SERVICE

#SERVICE REGISTRY PROPERTIES
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost